version: '3'
services:
    web:
        build: ./web
        ports:
            - '80:80'
        depends_on:
            - db
        environment:
            DB_PASSWORD: abcd
    db:
        build: ./db
        ports:
            - '3306:3306'
        environment:
            MARIADB_ROOT_PASSWORD: abcd
        volumes:
            - .dbdata:/var/lib/mysql
