version: '3.4'

x-default: &default
    environment:
        MARIADB_ROOT_PASSWORD: 'abcdefghchangeme'

services:
    web:
        build: ./web
        ports:
            - '80:80'
            - '443:443'
        depends_on:
            - db
        <<: *default
    db:
        build: ./db
        ports:
            - '3306:3306'
        volumes:
            - .dbdata:/var/lib/mysql
        <<: *default
